services:
  nasphoto:
    image: nasphoto:ci
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./dist:/app/dist:ro
      - ./data:/app/data:ro
      - /share/陈旭的文件夹/照片:/app/data/photos/陈旭的文件夹
      - /share/任宪美的文件夹/照片:/app/data/photos/任宪美的文件夹
    restart: always
